name: pr_lklm_checker             # workflow 名
on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches: [ main ]
env:
  base_branch: "main" 
  diff_path: "code/sample.lkml" #探索するファイル
  target_str: "hello" #探索する文字列の指定
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} #トークンの宣言。
  URL: ${{ github.event.pull_request.html_url }} #プルリクのURL。
jobs:
  build:  # job id
    name:  Check lklm strings # job 名
    runs-on: ubuntu-latest # 仮想環境指定（Windows Server, Ubuntu, Mac OSをサポートする）
    steps:
      - name: Switch to pull request branch
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Fetch base branch
        run: git fetch origin ${base_branch}:${base_branch}
      - name: check pattern 1 #差分内に${target_str} を含む場合に、プルリクにコメントし却下する。
        run: |
          gh pr comment -b "debug 
          $(
            cat ${diff_path} |  
            tr "\n" " " |
            grep 'constant:\s*model_name\s*{\s*value:\s*"picsr02_dev"\s*export:\s*override_required\s*}'
          )" \
            ${{github.event.pull_request.html_url }}
          if [[ $(
            cat ${diff_path} |  
            tr "\n" " " |
            grep 'constant:\s*model_name\s*{\s*value:\s*"picsr02_dev"\s*export:\s*override_required\s*}'
          ) == "" ]]; then
            gh pr comment -b "${diff_path}が変更されています。" \
            ${{github.event.pull_request.html_url }}
            exit 1
            echo "contains ${target_str}"
          fi
      - name: check pattern 2 #差分内に${target_str} を含む場合に、プルリクにコメントし却下する。
        run: |
          if [[ $(
            cat ${diff_path} |
            tr "\n" " " |
            grep 'constant:\s*model_name\s*{\s*export:\s*override_required\s*value:\s*"picsr02_dev"\s*}'
          ) == "" ]]; then
            gh pr comment -b "${diff_path}が変更されています。" \
            ${{github.event.pull_request.html_url }}
            exit 1
            echo "contains ${target_str}"
          fi