name: pr_diff_file_checker             # workflow 名
on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches: [ main ]
env:
  base_branch: "main" 
  exclude_path_1: "!:code/**" #探索する文字列の指定
  exclude_path_2: "!:configfile"
  target_str: "hoge" #探索する文字列の指定
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} #トークンの宣言。必要
  URL: ${{ github.event.pull_request.html_url }} #プルリクのURL。参照していないが、消すと動かない？
jobs:
  build:  # job id
    name:  Check Diff Important File # job 名
    runs-on: ubuntu-latest # 仮想環境指定（Windows Server, Ubuntu, Mac OSをサポートする）
    steps:
      - name: Switch to pull request branch
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Fetch base branch
        run: git fetch origin ${base_branch}:${base_branch}
      - name: Display file name if it contains hoge #差分内に${target_str} を含む場合に、プルリクにコメントし却下する。
        run: |
          diff_files=`git diff --name-only HEAD origin/${base_branch}\
           -- ${exclude_path_1} -- ${exclude_path_2} | tr "\n" " "`
          gh pr comment -b "${diff_files}が変更されています。" ${{github.event.pull_request.html_url }}
          if  {{${diff_files} != ""}}; then
            gh pr comment -b "${diff_files}が変更されています。" ${{github.event.pull_request.html_url }}
            exit 1
            echo "contains ${target_str}"
          fi