# PRを投げられた際に、指定のディレクトリ以外に変更がないことを確認するGitHubActions。
# 指定のディレクトリはexclude_pathで指定している。

name: pr_diff_file_checker             # workflow 名
on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches: [ main ]
    paths:
      - "!code/*"
      - "!.github/*"
      - "!cinfigfile" 
env:
  base_branch: "main" 
  exclude_path_1: ":!/code/*"
  exclude_path_3: ":!/.github/*"
  exclude_path_2: ":!/cinfigfile" #「:!」で取り除いて検索s
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} #トークンの宣言。必要
  URL: ${{ github.event.pull_request.html_url }} #プルリクのURL。参照していないが、消すと動かない？
jobs:
  build:  # job id
    name:  Check Diff Important File # job 名
    runs-on: ubuntu-latest # 仮想環境指定（Windows Server, Ubuntu, Mac OSをサポートする）
    steps:
    - name: Confirmation that critical files have not been modified #重要なファイルが変更されていないことを確認する
        run: exit 1