name: pr_hello_checker             # workflow 名
on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches: [ main ]
env:
  base_branch: "main" 
  diff_path: "code/**" #探索する文字列の指定
  target_str: "hello" #探索する文字列の指定
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} #トークンの宣言。
  URL: ${{ github.event.pull_request.html_url }} #プルリクのURL。
jobs:
  build:  # job id
    name:  Find hello strings # job 名
    runs-on: ubuntu-latest # 仮想環境指定（Windows Server, Ubuntu, Mac OSをサポートする）
    steps:
      - name: Switch to pull request branch
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Fetch base branch
        run: git fetch origin ${base_branch}:${base_branch}
      - name: Display file name if it contains hello #差分内に${target_str} を含む場合に、プルリクにコメントし却下する。
        run: |
          diff_files=`git diff --name-only  HEAD origin/${base_branch} -- ${diff_path} | tr "\n" " "`
          if grep -L ${target_str} ${diff_files} != ""; then
            gh pr comment -b "$(grep -L ${target_str} ${diff_files})に${target_str}が含まれていませんでした。" \
            ${{github.event.pull_request.html_url }}
            exit 1
            echo "contains ${target_str}"
          fi