name: pr_checker             # workflow 名
on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches: [ main ]
    paths: [ 'code/*.py' ]
env:
  base_branch: 'main'
  diff_path: 'code/*.py' #チェックするディレクトリと拡張子の指定
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} #トークンの宣言。必要
  URL: ${{ github.event.pull_request.html_url }} #プルリクのURL。参照していないが、消すと動かない？
jobs:
  build:  # job id
    name:  find hoge # job 名
    runs-on: ubuntu-latest # 仮想環境指定（Windows Server, Ubuntu, Mac OSをサポートする）
    steps:
      - name: checkout source code     # step 01 名
        uses: actions/checkout@master  # Source Code checkout

      - name: Run actions using diff_files #変更のあるファイルを抽出する。
        run: |
          echo "diff_files=git diff HEAD --name-only  ${base_branch} -- "${diff_path}" tr "\n" " "" >> $GITHUB_OUTPUT
      
      - name: Run test #変更のあるファイルを抽出する。
        run: |
          echo "${diff_files}"

      - name: Display file name if it contains hoge #差分内に[hoge] を含む場合に、プルリクにコメントし却下する。
        run: |
          if  grep -rE "hoge" ${diff_files}; then
            gh pr comment -b "contains hoge" ${{github.event.pull_request.html_url }}
            gh pr close ${{github.event.pull_request.html_url }}
            echo "contains hoge"
          fi












